// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ozdsnnqmmyawzsxheqmo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im96ZHNubnFtbXlhd3pzeGhlcW1vIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUyNDQ0MzQsImV4cCI6MjA2MDgyMDQzNH0.9aCf7iB_eim0Bs7p_bZuLhH6Ft2vz7-wECFwuYby9z0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);